{% set name = "opentelemetry-exporter-otlp-proto-http" %}
{% set version = "1.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-exporter-otlp-proto-http-{{ version }}.tar.gz
  sha256: 300339289095fa53aadf04022aa69a144389b8cc2f93d69edc164e5f944cfb9e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - backoff ~=1.10.0
    - googleapis-common-protos ~=1.52
    - opentelemetry-api ~=1.3
    - opentelemetry-proto ==1.10.0
    - opentelemetry-sdk ~=1.3
    - python >=3.6
    - requests ~=2.7

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-http
  summary: OpenTelemetry Collector Protobuf over HTTP Exporter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
