{% set name = "opentelemetry-exporter-otlp-proto-http" %}
{% set version = "1.26.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_http-{{ version }}.tar.gz
  sha256: 5801ebbcf7b527377883e6cbbdda35ee712dc55114fff1e93dfee210be56c908

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - deprecated >=1.2.6
    - googleapis-common-protos >=1.52,<2.dev0
    - opentelemetry-api >=1.15,<2.dev0
    - opentelemetry-proto ==1.26.0
    - opentelemetry-sdk >=1.26.0,<1.27.dev0
    - opentelemetry-exporter-otlp-proto-common ==1.26.0
    - requests >=2.7,<3.dev0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-http
  summary: OpenTelemetry Collector Protobuf over HTTP Exporter
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-http
  doc_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-http

extra:
  recipe-maintainers:
    - mariusvniekerk
