{% set name = "opentelemetry-exporter-otlp-proto-http" %}
{% set version = "1.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: f16bd44baf15cbe07633c5112ffc68229d0edbeac7b37610be0b2def4e21e90b

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - googleapis-common-protos >=1.52,<2
    - opentelemetry-api >=1.15,<2
    - opentelemetry-proto =={{ version }}
    - opentelemetry-sdk >=1.38.0,<1.39.0.dev
    - opentelemetry-exporter-otlp-proto-common =={{ version }}
    - requests >=2.7,<3
    - typing-extensions >=4.5.0

# E   ModuleNotFoundError: No module named 'opentelemetry.test'
# https://pypi.org/project/opentelemetry-test-utils, not in the main channel.
{% set ignore_tests = " --ignore=tests/metrics/test_otlp_metrics_exporter.py" %}
# Disabled unstable tests with timeouts:
{% set deselect_tests = " --deselect=tests/test_proto_log_exporter.py::TestOTLPHTTPLogExporter::test_retry_timeout" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_proto_span_exporter.py::TestOTLPSpanExporter::test_retry_timeout" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_proto_log_exporter.py::TestOTLPHTTPLogExporter::test_shutdown_interrupts_retry_backoff" %}
test:
  source_files:
    - tests
  imports:
    - opentelemetry.exporter.otlp.proto.http
  commands:
    - pip check
    - pytest -v tests {{ ignore_tests }} {{ deselect_tests }}
  requires:
    - pip
    - pytest >=7.4.4

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-http
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: OpenTelemetry Collector Protobuf over HTTP Exporter
  description: This library allows to export data to the OpenTelemetry Collector using the OpenTelemetry Protocol using Protobuf over HTTP.
  dev_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-http
  doc_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-http

extra:
  recipe-maintainers:
    - mariusvniekerk
