{% set name = "opentelemetry-exporter-otlp-proto-http" %}
{% set version = "1.12.0" %}
{% set sha256 = "01c7df992fa88ca1c8f130e0263ad0c820da2418b75a176667b75a5ba3a9e266" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - backoff <3.0.0,>=1.10.0
    - googleapis-common-protos >=1.52,<2.0a0
    - opentelemetry-api >=1.3,<2.0a0
    - opentelemetry-proto ==1.12.0
    - opentelemetry-sdk >=1.11,<2.0a0
    - requests >=2.7,<3.0a0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  summary: OpenTelemetry Python / Protobuf over HTTP Exporter
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-http
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://opentelemetry-python.readthedocs.io/
  doc_source_url: https://github.com/open-telemetry/opentelemetry-python/tree/main/docs
  dev_url: https://github.com/open-telemetry/opentelemetry-python
  description: |-
    OpenTelemetry, also known as OTel for short, is a vendor-neutral open-source
    Observability framework for instrumenting, generating, collecting, and exporting
    telemetry data such as traces, metrics, logs. As an industry-standard
    it is natively supported by a number of vendors.

extra:
  recipe-maintainers:
    - mariusvniekerk
